### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [w8floosh/quantum-fsm#1]
I recently came across your project quantum-fsm and I noticed that the repository github.com/w8floosh/quantum-fsm currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by w8floosh** [comment]
Hello,
thank you for getting in touch. Sure it is possible to add a license. Happy to come across someone who cares about this project :smile: 

I am going to add this in #2.

If you don't mind, I would be glad if you can tell me what are you working on and how did you find this project. Just curious :smile: 

Thank you again

**Comment by cbjuan** [comment]
Thank you!. I found your project navigating many repos that use Qiskit in GitHub
